// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/natanchagas/gin-crud/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// RealStateRepository is an autogenerated mock type for the RealStateRepository type
type RealStateRepository struct {
	mock.Mock
}

// CreateRealState provides a mock function with given fields: ctx, realState
func (_m *RealStateRepository) CreateRealState(ctx context.Context, realState domain.RealState) (int64, error) {
	ret := _m.Called(ctx, realState)

	if len(ret) == 0 {
		panic("no return value specified for CreateRealState")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.RealState) (int64, error)); ok {
		return rf(ctx, realState)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.RealState) int64); ok {
		r0 = rf(ctx, realState)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.RealState) error); ok {
		r1 = rf(ctx, realState)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRealStateRepository creates a new instance of RealStateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRealStateRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *RealStateRepository {
	mock := &RealStateRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
